const authController = 'api/v2';
const api = 'api';

export const SERVICE_CONFIG_URLS = {
  AUTH: {
    CHECK_USER: `${authController}/check-user`,
    LOGIN: `${authController}/login`,
    FOROGT_PASSWORD: `${authController}/forgot-password`,
    VERIFY_OTP: `${authController}/verify-otp`,
    SEND_OTP: `${authController}/send-otp`,
    RESET_PASSWORD: `${authController}/reset-password`,
    CREATE_ACCOUNT: `${authController}/register`,
    CITIES: `${authController}/external-cities`,
    DISTRICTS: `${authController}/external-districts`,
    CHART_DATA: `${authController}/external-get-amount-latest-mom`,
    PAYMENT_SAVE_CARD: `${authController}/save-card`,
  },
  APP: {
    CREATE_CHANNEX_ACCOUNT: `${authController}/create/channex/account/{user_id}`,
    GET_CHANNEX_ACCOUNT: `${authController}/channels/{user_id}`,
    GET_CHANNEX_LISTINGS: `${authController}/channex/listings/{channel_id}`,
    GET_USER_LISTINGS_BY_USER_ID: `${authController}/user/listings/{user}`,
    CREATE_MAP_LISTING_BY_USER_ID: `${authController}/mapListing/{user}`,
    CREATE_GATHERN_CREATE_CHANNEL: `${authController}/gathern/create-channel?user_id={user_id}`,
    GET_GATHERN_LISTING: `${authController}/gathern/listings?channel_id={channel_id}`,
    CREATE_LISTING: `${authController}/channelmanagement/create-listing`,
    CREATE_LISTING_DETAILS: `${authController}/channelmanagement/create-listing/details`,
    CREATE_LISTING_PRICING: `${authController}/channelmanagement/create-listing/pricing`,
    GET_MANAGE_YOUR_LISTINGS: `${authController}/user/listings/{user}`,
    GET_MANAGE_YOUR_LISTING_DETAIL: `${authController}/listing-details/{listing_id}`,
    EDIT_MANAGE_YOUR_LISTING_DETAIL: `${authController}/channelmanagement/create-listing/details`,
    EDIT_MANAGE_YOUR_LISTING_DETAIL_PRICE: `${authController}/channelmanagement/create-listing/pricing`,
    GET_CHAT_LIST: `${authController}/chat/inbox`,
    CREATE_CHAT_INBOX_ARCHIVE: `${authController}/chat/inbox/{conversation_id}/archive`,
    CREATE_CHAT_INBOX_UNARCHIVE: `${authController}/chat/inbox/{conversation_id}/unarchive`,
    CREATE_CHAT_INBOX_SNOOZE: `${authController}/chat/inbox/{conversation_id}/snooze`,
    CREATE_CHAT_INBOX_UNSNOOZE: `${authController}/chat/inbox/{conversation_id}/unsnooze`,
    CREATE_USER_MANAGEMENT: `${authController}/host/users`,
    GET_USER_MANAGEMENT_LISTING: `${authController}/host/users/listings`,
    GET_USER_MANAGEMENT_ROLE: `${authController}/host/users/role`,
    GET_USER_MANAGEMENT: `${authController}/host/users`,
    EDIT_USER_MANAGEMENT: `${authController}/host/users/{id}`,
    DELETE_USER_MANAGEMENT: `${authController}/host/users/{id}`,
    GET_CHAT_LIST_CITY: `${authController}/states`,
    GET_SAVED_REPLIES: `${authController}/chat/saved-replies`,
    CREATE_SAVED_REPLIES: `${authController}/chat/saved-replies`,
    EDIT_SAVED_REPLIES: `${authController}/chat/saved-replies/{id}`,
    EDIT_STATUS_SAVED_REPLIES: `${authController}/chat/saved-replies/{id}/status`,
    DELETE_SAVED_REPLIES: `${authController}/chat/saved-replies/{id}`,
    GET_AUTOMATIONS_TEMPLATE: `${authController}/chat/automations`,
    CREATE_AUTOMATIONS_TEMPLATE: `${authController}/chat/automations`,
    EDIT_AUTOMATIONS_TEMPLATE: `${authController}/chat/automations/{id}`,
    DELETE_AUTOMATIONS_TEMPLATE: `${authController}/chat/automations/{id}`,
    GET_AUTOMATIONS_TEMPLATE_MESSAGE_VARIABLES: `${authController}/chat/message-templates/variables`,
    GET_AUTOMATIONS_TEMPLATE_EVENTS: `${authController}/chat/automations/events`,
    EDIT_STATUS_AUTOMATIONS_TEMPLATE: `${authController}/chat/automations/{id}/status`,
    GET_CHAT_DETAIL: `${authController}/chat/inbox/{conversation_id}`,
    GET_AI_AUTO_REPLY: `${authController}/chat/ai/rules`,
    CREATE_AI_AUTO_REPLY: `${authController}/chat/ai/rules`,
    EDIT_AI_AUTO_REPLY: `${authController}/chat/ai/rules/{id}`,
    DELETE_AI_AUTO_REPLY: `${authController}/chat/ai/rules/{id}`,
    EDIT_STATUS_AI_AUTO_REPLY: `${authController}/chat/ai/rules/{id}/status`,
    GET_CATEGORY_TASK_MANAGEMENT: `${api}/task-types`,
    GET_LISTING_TASK_MANAGEMENT: `${api}/host-active-listings`,
    GET_VENDOR_TASK_MANAGEMENT: `${api}/host-vendors`,
    CREATE_TASK_MANAGEMENT: `${api}/host-create-task`,
    GET_TASK_MANAGEMENT_CHECKLIST: `${api}/get-task-checklist/{id}/{tasktype}`,
    GET_TASK_MANAGEMENT_CHECKLIST_DETAIL: `${api}/get-task-checklist_detailed/{id}/{tasktype}`,
    TASK_MANAGEMENT_INSERT_CHECKLIST: `${api}/add-checklist-item`,
    TASK_MANAGEMENT_ADD_SECTION: `${api}/add-checklist-section`,
    TASK_MANAGEMENT_SINGLE_CHECKLIST_ITEM_UPDATE: `${api}/task/checklist/update`,
    TASK_MANAGEMENT_STATUS_UPDATE: `${api}/task-draft-to-create`,
    GET_HOST_TASK_LIST: `${api}/get-host-tasklist`,
    TASK_MANAGEMENT_TASK_DETAIL: `${api}/gettaskdetails/{taskid}`,
    TASK_MANAGEMENT_VENDOR_UPDATE: `${api}/host-task-edit/{id}`,
  },
};
