const STORAGE_CONST = {
    CITIES: 'CITIES',
    DISTRICTS: 'DISTRICTS',
    CHART_DATA: 'CHART_DATA',
    GET_CHANNELS_USER:'GET_CHANNELS_USER',
    GET_AIRBNB_IMPORT_LISTING:'GET_AIRBNB_IMPORT_LISTING',
    GET_USER_LISTINGS_USER_ID:'GET_USER_LISTINGS_USER_ID',
    CREATE_MAP_LISITNG_USER_ID:'CREATE_MAP_LISITNG_USER_ID',
    GET_GATHERN_LISTINGS_USER_ID:'GET_GATHERN_LISTINGS_USER_ID',
    MANAGE_YOUR_LISTINGS:'MANAGE_YOUR_LISTINGS',
    MANAGE_YOUR_LISTINGS_PROPERTY_DETAIL:'MANAGE_YOUR_LISTINGS_PROPERTY_DETAIL',
    GET_CHAT_LIST:'GET_CHAT_LIST',
    GET_CHAT_LIST_CITY:'GET_CHAT_LIST_CITY',
    GET_USER_MANAGEMENT_LISTING:'GET_USER_MANAGEMENT_LISTING',
    GET_USER_MANAGEMENT_ROLES:'GET_USER_MANAGEMENT_ROLES',
    GET_USER_MANAGEMENT:'GET_USER_MANAGEMENT',
    GET_CHAT_DETAIL:'GET_CHAT_DETAIL',
    GET_SAVED_REPLIES:'GET_SAVED_REPLIES',
    GET_AUTOMATION_TEMPLATE:'GET_AUTOMATION_TEMPLATE'


}

export default STORAGE_CONST;