const STORAGE_CONST = {
    CITIES: 'CITIES',
    DISTRICTS: 'DISTRICTS',
    CHART_DATA: 'CHART_DATA',
    GET_CHANNELS_USER:'GET_CHANNELS_USER',
    GET_AIRBNB_IMPORT_LISTING:'GET_AIRBNB_IMPORT_LISTING',
    GET_USER_LISTINGS_USER_ID:'GET_USER_LISTINGS_USER_ID',
    CREATE_MAP_LISITNG_USER_ID:'CREATE_MAP_LISITNG_USER_ID',
    GET_GATHERN_LISTINGS_USER_ID:'GET_GATHERN_LISTINGS_USER_ID',
    MANAGE_YOUR_LISTINGS:'MANAGE_YOUR_LISTINGS',
    MANAGE_YOUR_LISTINGS_PROPERTY_DETAIL:'MANAGE_YOUR_LISTINGS_PROPERTY_DETAIL',


}

export default STORAGE_CONST;