const STORAGE_CONST = {
    CITIES: 'CITIES',
    DISTRICTS: 'DISTRICTS',
    CHART_DATA: 'CHART_DATA',
    GET_CHANNELS_USER:'GET_CHANNELS_USER',
    GET_AIRBNB_IMPORT_LISTING:'GET_AIRBNB_IMPORT_LISTING',
    GET_USER_LISTINGS_USER_ID:'GET_USER_LISTINGS_USER_ID',
    CREATE_MAP_LISITNG_USER_ID:'CREATE_MAP_LISITNG_USER_ID',
}

export default STORAGE_CONST;