const NavigationRoutes = {
  AUTH_STACK: {
    LOGIN_WITH_PHONE: 'LOGIN_WITH_PHONE_SCREEN',
    ON_BOARDING: 'ON_BOARDING_SCREEN',
    PROPERTY_CAN_EARN: 'PROPERTY_CAN_EARN_SCREEN',
    CONNECT_CALENDARS_INTRO: 'CONNECT_CALENDARS_INTRO_SCREEN',
    AGENT_INTRO: 'AGENT_INTRO_SCREEN',
    VERIFY_PHONE_NUMBER: 'VERIFY_PHONE_NUMBER_SCREEN',
    MANAGE_LISTING: 'MANAGE_LISTING_SCREEN',
    CREATE_ACCOUNT: 'CREATE_ACCOUNT_SCREEN',
    ENTER_PASSWORD:'ENTER_PASSWORD_SCREEN',
    ADD_NEW_PASSWORD:'ADD_NEW_PASSWORD_SCREEN',
    PAYMENT:'PAYMENT_SCREEN',
    ADD_CARD_DETAIL:'ADD_CARD_DETAIL_SCREEN',
    TRIAL_SUCCESS:'TRIAL_SUCCESS_SCREEN'

  },
  APP_STACK: {
    ROOT_STACK: 'ROOT_STACK',
    HOME: 'HOME_SCREEN',
  },

  ROOT_STACK: {},
};

export default NavigationRoutes;
